# words.py — Unitlar va so'zlar bazasi

UNITS = {
    1: [
        {"word": "Afraid", "trans": "Qorqqan, chochigan", "ex": "The woman was afraid of the dark."},
        {"word": "Agree", "trans": "Rozi bolmoq, qoshilmoq", "ex": "A: The food is delicious. B: I agree."},
        {"word": "Angry", "trans": "Jahli chiqqan", "ex": "She was angry because he was late."},
        {"word": "Arrive", "trans": "Yetib kelmoq", "ex": "They arrived at the station in time."},
        {"word": "Attack", "trans": "Hujum qilmoq", "ex": "The dog attacked the mailman."},
        {"word": "Bottom", "trans": "Tub, pastki qism", "ex": "The bottom of my shoe has a hole in it."},
        {"word": "Clever", "trans": "Aqlli, zukko", "ex": "The clever boy solved the puzzle quickly."},
        {"word": "Cruel", "trans": "Zolim, shafqatsiz", "ex": "The cruel man yelled at the poor dog."},
        {"word": "Finally", "trans": "Axiri, nihoyat", "ex": "He finally crossed the finish line."},
        {"word": "Hide", "trans": "Yashirinmoq", "ex": "The child hid behind the tree."},
        {"word": "Hunt", "trans": "Ov qilmoq", "ex": "The cats hunt mice in the garden."},
        {"word": "Lot", "trans": "Juda ko'p", "ex": "There are a lot of apples in the basket."},
        {"word": "Middle", "trans": "O'rta", "ex": "The table is in the middle of the room."},
        {"word": "Moment", "trans": "Lahza, bir pas", "ex": "Wait a moment, please."},
        {"word": "Promise", "trans": "Va'da bermoq", "ex": "He promised to help me with my homework."},
        {"word": "Reply", "trans": "Javob bermoq", "ex": "She replied to my email quickly."},
        {"word": "Safe", "trans": "Xavfsiz", "ex": "Put your money in a safe place."},
        {"word": "Trick", "trans": "Ayorlik, hiyla", "ex": "The magician performed a clever trick."},
        {"word": "Well", "trans": "Yaxshi", "ex": "He speaks English very well."},
        {"word": "Adventure", "trans": "Sarguzasht", "ex": "Riding a coaster was a thrill adventure."}
    ],
    2: [
        {"word": "Adventure", "trans": "Sarguzasht", "ex": "Riding a coaster was a thrill adventure."},
        {"word": "Approach", "trans": "Yaqinlashmoq", "ex": "The train was approaching the station."},
        {"word": "Carefully", "trans": "Ehtiyotkorlik bilan", "ex": "He carefully carried the box."},
        {"word": "Chemical", "trans": "Kimyoviy modda", "ex": "The scientist mixed the chemicals."},
        {"word": "Create", "trans": "Yaratmoq", "ex": "She created a masterpiece painting."},
        {"word": "Evil", "trans": "Yomon, yovuz", "ex": "The evil witch cast a spell."},
        {"word": "Experiment", "trans": "Tajriba", "ex": "They performed a lab experiment."},
        {"word": "Kill", "trans": "O'ldirmoq", "ex": "Frost can kill young plants."},
        {"word": "Laboratory", "trans": "Laboratoriya", "ex": "They work in a research laboratory."},
        {"word": "Laugh", "trans": "Kulgu, kulmoq", "ex": "Her laugh was loud and clear."},
        {"word": "Loud", "trans": "Baland, shovqinli", "ex": "The music was too loud."},
        {"word": "Nervous", "trans": "Xavotirlangan", "ex": "He felt nervous before the exam."},
        {"word": "Noise", "trans": "Shovqin", "ex": "The car made a strange noise."},
        {"word": "Project", "trans": "Loyiha", "ex": "Our class project is about space."},
        {"word": "Scare", "trans": "Qorqitmoq", "ex": "The loud boom scared the birds."},
        {"word": "Secret", "trans": "Sirlilik, sir", "ex": "Keep this a secret between us."},
        {"word": "Shout", "trans": "Baqirmoq", "ex": "Don't shout at each other."},
        {"word": "Smell", "trans": "Hidi, hidlamoq", "ex": "The flower has a sweet smell."},
        {"word": "Terrible", "trans": "Juda yomon, daxshatli", "ex": "There was a terrible accident."},
        {"word": "Worse", "trans": "Yomonroq", "ex": "The weather today is worse."}
    ],
    3: [
        {"word": "Alien", "trans": "Ozg'a, begona", "ex": "The movie was about aliens."},
        {"word": "Among", "trans": "O'rtasida, orasida", "ex": "He walked among the trees."},
        {"word": "Chart", "trans": "Jadval, diagramma", "ex": "Look at the sales chart."},
        {"word": "Cloud", "trans": "Bulut", "ex": "The sky was full of clouds."},
        {"word": "Comprehend", "trans": "Tushunmoq", "ex": "I cannot comprehend this rule."},
        {"word": "Describe", "trans": "Tasvirlamoq", "ex": "Describe your best friend."},
        {"word": "Ever", "trans": "Qachondir, hech", "ex": "Have you ever been to Paris?"},
        {"word": "Fail", "trans": "Muvaffaqiyatsizlikka uchramoq", "ex": "He did not want to fail."},
        {"word": "Friendly", "trans": "Do'stona", "ex": "The people here are friendly."},
        {"word": "Grade", "trans": "Baho, daraja", "ex": "She got a good grade."},
        {"word": "Instead", "trans": "O'rniga", "ex": "We used tea instead of coffee."},
        {"word": "Library", "trans": "Kutubxona", "ex": "He reads in the library."},
        {"word": "Planet", "trans": "Sayyora", "ex": "Earth is our home planet."},
        {"word": "Report", "trans": "Hisobot, xabar", "ex": "He wrote a detailed report."},
        {"word": "Several", "trans": "Bir nechta", "ex": "There are several choices."},
        {"word": "Solve", "trans": "Yechmoq (masala)", "ex": "Can you solve this puzzle?"},
        {"word": "Suddenly", "trans": "To'satdan", "ex": "Suddenly, the lights went out."},
        {"word": "Suppose", "trans": "Deb o'ylamoq", "ex": "I suppose you are right."},
        {"word": "Universe", "trans": "Koinot", "ex": "The universe is vast."},
        {"word": "View", "trans": "Ko'rinish, manzara", "ex": "The view from the top was nice."}
    ],
    4: [
        {"word": "Appropriate", "trans": "Munosib, to'g'ri", "ex": "Wear appropriate clothing."},
        {"word": "Avoid", "trans": "Qochmoq, saqlanmoq", "ex": "Avoid eating sugar."},
        {"word": "Behave", "trans": "O'zini tutmoq", "ex": "Behave yourself in class."},
        {"word": "Calm", "trans": "Xotirjam, tinch", "ex": "Stay calm during a storm."},
        {"word": "Concern", "trans": "Tashvish, qayg'u", "ex": "Health is my main concern."},
        {"word": "Expect", "trans": "Kutmoq, umid qilmoq", "ex": "I expect good news today."},
        {"word": "Frequently", "trans": "Tez-tez", "ex": "He visits us frequently."},
        {"word": "Habit", "trans": "Odat", "ex": "Reading daily is a good habit."},
        {"word": "Instruct", "trans": "Ko'rsatma bermoq", "ex": "Instruct him on what to do."},
        {"word": "Issue", "trans": "Muammo, masala", "ex": "We discussed the main issue."},
        {"word": "None", "trans": "Hech qaysi", "ex": "None of the answers are correct."},
        {"word": "Patient", "trans": "Sabrli", "ex": "Be patient with children."},
        {"word": "Positive", "trans": "Ijobiy", "ex": "Think positive thoughts."},
        {"word": "Punish", "trans": "Jazolamoq", "ex": "Do not punish the mistake."},
        {"word": "Represent", "trans": "Vakillik qilmoq", "ex": "He represents our country."},
        {"word": "Shake", "trans": "Siltamoq, silkitmoq", "ex": "Shake hands after the meeting."},
        {"word": "Spread", "trans": "Tarqalmoq", "ex": "News spreads very fast."},
        {"word": "Stroll", "trans": "Aylanib yurmoq", "ex": "We took a stroll in the park."},
        {"word": "Village", "trans": "Qishloq", "ex": "My grandparents live in a village."},
        {"word": "Aware", "trans": "Xabardor", "ex": "Be aware of the rules."}
    ],
    5: [
        {"word": "Aware", "trans": "Xabardor", "ex": "I am aware of the risk."},
        {"word": "Badly", "trans": "Yomon darajada", "ex": "He did badly on the test."},
        {"word": "Belong", "trans": "Tegishli bo'lmoq", "ex": "This book belongs to me."},
        {"word": "Continue", "trans": "Davom ettirmoq", "ex": "Please continue reading."},
        {"word": "Error", "trans": "Xato", "ex": "Fix the error in your code."},
        {"word": "Experience", "trans": "Tajriba", "ex": "He has work experience."},
        {"word": "Field", "trans": "Dala, maydon", "ex": "Cows graze in the field."},
        {"word": "Hurt", "trans": "O'g'ritmoq, jarohatlamoq", "ex": "My leg hurts a bit."},
        {"word": "Judgment", "trans": "Xulosa, qaror", "ex": "Trust your own judgment."},
        {"word": "Likely", "trans": "Ehtimoli bor", "ex": "It is likely to rain."},
        {"word": "Normal", "trans": "Odatiy, normal", "ex": "Everything is normal here."},
        {"word": "Rare", "trans": "Kamdan-kam, noyob", "ex": "This bird is very rare."},
        {"word": "Relax", "trans": "Hordiq chiqarmoq", "ex": "Relax after a long day."},
        {"word": "Request", "trans": "Iltimos qilmoq", "ex": "I request your attention."},
        {"word": "Reside", "trans": "Yashamoq, istiqomat qilmoq", "ex": "They reside in the capital."},
        {"word": "Result", "trans": "Natija", "ex": "The test results came back."},
        {"word": "Roll", "trans": "Aylanmoq, dumalamoq", "ex": "The ball rolled down the hill."},
        {"word": "Since", "trans": "-dan beri", "ex": "I have lived here since 2010."},
        {"word": "Visible", "trans": "Ko'rinadigan", "ex": "The stars are visible tonight."},
        {"word": "Wild", "trans": "Yovvoyi", "ex": "Lions are wild animals."}
    ],
    6: [
        {"word": "Advantage", "trans": "Afzallik, ustunlik", "ex": "Being tall is an advantage in basketball."},
        {"word": "Cause", "trans": "Sabab bo'lmoq", "ex": "Smoking can cause health problems."},
        {"word": "Choice", "trans": "Tanlov", "ex": "You have a choice between coffee or tea."},
        {"word": "Community", "trans": "Jamoa, jamiyat", "ex": "He is well known in the local community."},
        {"word": "Distance", "trans": "Masofa", "ex": "The distance from my home to school is short."},
        {"word": "Escape", "trans": "Qochib qutulmoq", "ex": "The bird escaped from the cage."},
        {"word": "Face", "trans": "Yuzma-yuz kelmoq, duch kelmoq", "ex": "We must face our fears."},
        {"word": "Follow", "trans": "Ertashmoq, izidan bormoq", "ex": "Follow the path to reach the lake."},
        {"word": "Fright", "trans": "Qorquv, vahima", "ex": "The loud noise gave me a fright."},
        {"word": "Ghost", "trans": "Arvoh", "ex": "Many people believe in ghosts."},
        {"word": "Individual", "trans": "Alohida shaxs, individ", "ex": "Each individual has unique talents."},
        {"word": "Pet", "trans": "Uy hayvoni", "ex": "She has a pet dog named Max."},
        {"word": "Reach", "trans": "Yetib bormoq", "ex": "We reached the top of the mountain."},
        {"word": "Return", "trans": "Qaytmoq", "ex": "He will return from his trip tomorrow."},
        {"word": "Survive", "trans": "Tirik qolmoq", "ex": "Plants need water to survive."},
        {"word": "Upset", "trans": "Xafa, tushkun", "ex": "She was upset about losing her keys."},
        {"word": "Voice", "trans": "Ovozi", "ex": "She has a beautiful singing voice."},
        {"word": "Weather", "trans": "Ob-havo", "ex": "The weather today is sunny and clear."},
        {"word": "Wise", "trans": "Oqil, dono", "ex": "The old man gave wise advice."},
        {"word": "Allow", "trans": "Ruxsat bermoq", "ex": "My parents allow me to stay out late."}
    ],
    7: [
        {"word": "Allow", "trans": "Ruxsat bermoq", "ex": "My parents allow me to stay out late."},
        {"word": "Announce", "trans": "E'lon qilmoq", "ex": "They announced the winner of the contest."},
        {"word": "Beside", "trans": "Yonida", "ex": "Sit beside me on the bench."},
        {"word": "Challenge", "trans": "Qiyinchilik, chaqiriq", "ex": "Learning Python is a fun challenge."},
        {"word": "Claim", "trans": "Ta'kidlamoq, da'vo qilmoq", "ex": "He claimed he saw a ghost."},
        {"word": "Condition", "trans": "Holat, sharoit", "ex": "The car is in very good condition."},
        {"word": "Contribute", "trans": "Hissa qo'shmoq", "ex": "Everyone should contribute to the team."},
        {"word": "Difference", "trans": "Farq", "ex": "Can you spot the difference between them?"},
        {"word": "Divide", "trans": "Bo'lmoq, ajratmoq", "ex": "Divide the cake into six slices."},
        {"word": "Expert", "trans": "Mutaxassis", "ex": "He is an expert in computer science."},
        {"word": "Famous", "trans": "Mashhur", "ex": "Barcelona is a famous football club."},
        {"word": "Force", "trans": "Kuch, majburlamoq", "ex": "You cannot force someone to agree."},
        {"word": "Harm", "trans": "Zaror, ziyon", "ex": "Too much sugar can harm your teeth."},
        {"word": "Lay", "trans": "Qo'ymoq, joylashtirmoq", "ex": "Lay the book down on the desk."},
        {"word": "Peace", "trans": "Tinchlik", "ex": "Everyone hopes for world peace."},
        {"word": "Prince", "trans": "Shahzoda", "ex": "The prince lived in a grand castle."},
        {"word": "Protect", "trans": "Himoya qilmoq", "ex": "A helmet protects your head."},
        {"word": "Sense", "trans": "His qilmoq, sezmoq", "ex": "I sense that something is wrong."},
        {"word": "Sudden", "trans": "To'satdan bo'lgan", "ex": "A sudden rain soaked us completely."},
        {"word": "Therefore", "trans": "Shuning uchun", "ex": "He studied hard; therefore, he passed."}
    ],
    8: [
        {"word": "Accept", "trans": "Qabul qilmoq", "ex": "She accepted the job offer."},
        {"word": "Arrange", "trans": "Tartibga solmoq, rejalashtirmoq", "ex": "I will arrange a meeting for tomorrow."},
        {"word": "Attend", "trans": "Qatnashmoq", "ex": "He attends school every morning."},
        {"word": "Balance", "trans": "Muvozanat", "ex": "Keep your balance on the ice."},
        {"word": "Contrast", "trans": "Taqqoslamoq, qarama-qarshilik", "ex": "There is a sharp contrast between them."},
        {"word": "Encourage", "trans": "Ruhlantirmoq, qo'llab-quvvatlamoq", "ex": "My teacher encouraged me to try."},
        {"word": "Familiar", "trans": "Tanish", "ex": "His face looks very familiar."},
        {"word": "Grab", "trans": "Ushlab olmoq, changallamoq", "ex": "Grab your bag and let's go."},
        {"word": "Hang", "trans": "Ilib qo'ymoq", "ex": "Hang your coat on the hook."},
        {"word": "Huge", "trans": "Juda katta, ulkan", "ex": "An elephant is a huge animal."},
        {"word": "Necessary", "trans": "Zurur, kerakli", "ex": "Water is necessary for life."},
        {"word": "Pattern", "trans": "Nusxa, namuna, naqsh", "ex": "The shirt has a striped pattern."},
        {"word": "Propose", "trans": "Taklif qilmoq", "ex": "He proposed a new plan for the project."},
        {"word": "Purpose", "trans": "Maqsad", "ex": "What is the main purpose of this tool?"},
        {"word": "Release", "trans": "Ozo'd qilmoq, chiqarmoq", "ex": "Release the bird back into nature."},
        {"word": "Require", "trans": "Talab qilmoq", "ex": "This job requires good math skills."},
        {"word": "Single", "trans": "Yagona, bitta", "ex": "There was not a single cloud in the sky."},
        {"word": "Success", "trans": "Muvaffaqiyat", "ex": "Hard work leads to success."},
        {"word": "Tear", "trans": "Yirtmoq", "ex": "Be careful not to tear the paper."},
        {"word": "Theory", "trans": "Nazariya", "ex": "Scientists tested the new theory."}
    ],
    9: [
        {"word": "Against", "trans": "Qarshi", "ex": "We played against a strong team."},
        {"word": "Beach", "trans": "Sohil, plyaj", "ex": "We spent the day at the beach."},
        {"word": "Damage", "trans": "Zarar yetkazmoq", "ex": "The storm caused heavy damage."},
        {"word": "Discover", "trans": "Kashf etmoq, topmoq", "ex": "They discovered a new star."},
        {"word": "Emotion", "trans": "Xis-tuyg'u", "ex": "Fear is a powerful emotion."},
        {"word": "Fix", "trans": "Tuzatmoq, ta'mirlamoq", "ex": "Can you fix my broken bike?"},
        {"word": "Frank", "trans": "Ochiqko'ngil, samimiy", "ex": "To be frank, I don't agree."},
        {"word": "Identify", "trans": "Aqlamoq, aniqlamoq", "ex": "Can you identify this object?"},
        {"word": "Island", "trans": "Orol", "ex": "They live on a tropical island."},
        {"word": "Ocean", "trans": "Okean", "ex": "The ocean waves were huge."},
        {"word": "Perhaps", "trans": "Ehtimol, balki", "ex": "Perhaps it will rain later today."},
        {"word": "Pleasant", "trans": "Yoqimli", "ex": "We had a pleasant walk."},
        {"word": "Prevent", "trans": "Oldini olmoq", "ex": "Wash hands to prevent sickness."},
        {"word": "Rock", "trans": "Tosh", "ex": "He threw a rock into the river."},
        {"word": "Save", "trans": "Saqlab qolmoq, tejamoq", "ex": "Save your money for the future."},
        {"word": "Step", "trans": "Qadam bosmoq, qadam", "ex": "Take one step forward."},
        {"word": "Still", "trans": "Hali ham", "ex": "He is still waiting outside."},
        {"word": "Taste", "trans": "Maza, ta'm", "ex": "This soup has a delicious taste."},
        {"word": "Throw", "trans": "Otmoq, uloqtirmoq", "ex": "Throw the ball to me."},
        {"word": "Wave", "trans": "To'lqin", "ex": "Surfers love big waves."}
    ],
    10: [
        {"word": "Benefit", "trans": "Foyda, naf", "ex": "Exercise brings many health benefits."},
        {"word": "Certain", "trans": "Aniq, ishonchi komil", "ex": "I am certain that I locked the door."},
        {"word": "Chance", "trans": "Imkoniyat, imkon", "ex": "Give him a second chance."},
        {"word": "Effect", "trans": "Ta'sir, natija", "ex": "The medicine had a fast effect."},
        {"word": "Essential", "trans": "Juda muhim, asosiy", "ex": "Sleep is essential for health."},
        {"word": "Far", "trans": "Uzoq", "ex": "His house is not far from here."},
        {"word": "Focus", "trans": "Diqqatni qaratmoq", "ex": "Focus on your studies."},
        {"word": "Function", "trans": "Vazifa, funksiya", "ex": "What is the function of this button?"},
        {"word": "Grass", "trans": "O't, maysazor", "ex": "Don't step on the green grass."},
        {"word": "Guard", "trans": "Qorovul, qo'riqlamoq", "ex": "A guard stands at the gate."},
        {"word": "Image", "trans": "Tasvir, rasm", "ex": "The camera captured a clear image."},
        {"word": "Immediate", "trans": "Darhol, tezkor", "ex": "This problem needs immediate attention."},
        {"word": "Primary", "trans": "Asosiy, birinchi darajali", "ex": "My primary goal is to learn English."},
        {"word": "Proud", "trans": "Mag'rur, faxrlanuvchi", "ex": "Parents are proud of their kids."},
        {"word": "Remain", "trans": "Qolmoq", "ex": "Please remain seated."},
        {"word": "Rest", "trans": "Dam olmoq", "ex": "Sit down and rest a bit."},
        {"word": "Separate", "trans": "Alohida, ajratilgan", "ex": "They sleep in separate rooms."},
        {"word": "Site", "trans": "Joy, maydon", "ex": "This is the site for the new school."},
        {"word": "Tail", "trans": "Dum", "ex": "The dog wagged its tail."},
        {"word": "Trouble", "trans": "Muammo, tashvish", "ex": "He got into trouble at school."}
    ],
    11: [
        {"word": "Anymore", "trans": "Ortiq, boshqa", "ex": "Her old pants don't fit her anymore."},
        {"word": "Asleep", "trans": "Uxlayotgan, uyquda", "ex": "The baby has been asleep for hours."},
        {"word": "Berry", "trans": "Malina, meva", "ex": "The berry looked delicious."},
        {"word": "Collect", "trans": "To'plamoq, yig'moq", "ex": "I collected shells when I was younger."},
        {"word": "Compete", "trans": "Musobaqalashmoq", "ex": "He will compete with very good athletes."},
        {"word": "Conversation", "trans": "Suhbat, muloqot", "ex": "There were two conversations going on at once."},
        {"word": "Creature", "trans": "Jonivor, tirik mavjudot", "ex": "The creature was a strange, hairy thing."},
        {"word": "Decision", "trans": "Qaror", "ex": "He made the wrong decision."},
        {"word": "Either", "trans": "Ikkisidan biri", "ex": "You can choose to be either white or black when you play chess."},
        {"word": "Forest", "trans": "O'rmon", "ex": "I love to go walking in the forest."},
        {"word": "Ground", "trans": "Yer", "ex": "The ground under our feet was dry and brown."},
        {"word": "Introduce", "trans": "Tanishtirmoq", "ex": "I introduced myself to our newest co-worker today."},
        {"word": "Marry", "trans": "Turmush qurmoq", "ex": "Rose and Henry were married, and they lived happily."},
        {"word": "Prepare", "trans": "Tayyorlanmoq, tayyorlamoq", "ex": "I prepared my speech to the class."},
        {"word": "Sail", "trans": "Qayiqda suzmoq; suzib ketmoq", "ex": "I love to sail my boat on the lake."},
        {"word": "Serious", "trans": "Jiddiy, og'ir", "ex": "The accident was very serious."},
        {"word": "Spend", "trans": "O'tkazmoq, sarflamoq", "ex": "I like to spend my free time fishing."},
        {"word": "Strange", "trans": "Noodatiy, g'alati", "ex": "Joe had a strange look on his face after he saw what happened."},
        {"word": "Truth", "trans": "Haqiqat", "ex": "He was telling the truth about seeing a large green snake."},
        {"word": "Wake", "trans": "Uyg'onmoq", "ex": "He is always full of energy when he wakes in the morning."}
    ],
    12: [
        {"word": "Alone", "trans": "Yolg'iz", "ex": "The boy wanted to be alone to think."},
        {"word": "Apartment", "trans": "Kvartira", "ex": "She has a nice apartment in the city."},
        {"word": "Article", "trans": "Maqola", "ex": "Did you read the article in the newspaper about the soccer game?"},
        {"word": "Artist", "trans": "Rassom", "ex": "He went to Paris to become an artist."},
        {"word": "Attitude", "trans": "Munosabat, muomala", "ex": "John has a bad attitude. He's always angry."},
        {"word": "Compare", "trans": "Taqqoslamoq, solishtirmoq", "ex": "If you compare cats and dogs, you'll see that they're both good pets."},
        {"word": "Judge", "trans": "Baho bermoq", "ex": "The boy was going to judge how his mother's turkey tasted."},
        {"word": "Magazine", "trans": "Jurnal", "ex": "She likes to read fashion magazines."},
        {"word": "Material", "trans": "Material, xomashyo", "ex": "Brick is a good material for building houses."},
        {"word": "Meal", "trans": "Ovqatlanish payti; taom", "ex": "Breakfast is my favorite meal because I enjoy breakfast foods."},
        {"word": "Method", "trans": "Metod, usul", "ex": "One method to remember things is to tie a string around your finger."},
        {"word": "Neighbor", "trans": "Qo'shni", "ex": "I like my neighbor because he's very friendly."},
        {"word": "Professional", "trans": "Kasbiy, professional", "ex": "If you want to be a pilot, you must have professional training."},
        {"word": "Profit", "trans": "Foyda", "ex": "I made a small profit from selling my old clothes."},
        {"word": "Quality", "trans": "Sifat", "ex": "The quality of his car is very good."},
        {"word": "Shape", "trans": "Shakl", "ex": "The triangle is my favorite shape."},
        {"word": "Space", "trans": "Bo'sh joy", "ex": "I don't have much space for things in my small house."},
        {"word": "Stair", "trans": "Zina, pillapoya", "ex": "You can take the stairs to the second floor."},
        {"word": "Symbol", "trans": "Ramz, belgi", "ex": "This symbol tells us that we cannot smoke in this area."},
        {"word": "Thin", "trans": "Oriq, ozg'in", "ex": "The man was thin because he didn't eat much."}
    ],
    13: [
        {"word": "Blood", "trans": "Qon", "ex": "I cut my finger and got blood on my shirt."},
        {"word": "Burn", "trans": "Olovda yoqmoq", "ex": "I burned some wood in the camp fire."},
        {"word": "Cell", "trans": "Kamera (turmada)", "ex": "The jail cell was very small."},
        {"word": "Contain", "trans": "O'z ichiga olmoq", "ex": "The mailbox contained a letter."},
        {"word": "Correct", "trans": "To'g'ri, bexato", "ex": "All of my answers on the test were correct."},
        {"word": "Crop", "trans": "Hosil, o'rim", "ex": "Wheat is a crop that is made into bread."},
        {"word": "Demand", "trans": "Talab qilmoq", "ex": "The workers demanded to be paid more money."},
        {"word": "Equal", "trans": "Teng, barobar", "ex": "Both students are equal in age."},
        {"word": "Feed", "trans": "Ovqatlantirmoq, ovqat bermoq", "ex": "Mother feeds my baby brother everyday."},
        {"word": "Hole", "trans": "Teshik, chuqurcha", "ex": "The man was going to jump into the hole in the ice."},
        {"word": "Increase", "trans": "Oshirmoq, ko'tarmoq", "ex": "They've increased the price of gas by 15 cents!"},
        {"word": "Lord", "trans": "Lord", "ex": "The lord of the town was not kind."},
        {"word": "Owe", "trans": "Qarz bo'lmoq", "ex": "I owed him twenty dollars, so I paid him back."},
        {"word": "Position", "trans": "Pozitsiya, holat", "ex": "How can you sit in that position?"},
        {"word": "Raise", "trans": "Ko'tarmoq", "ex": "We had to work together to raise the last piece."},
        {"word": "Responsible", "trans": "Aqlli, mas'uliyatli", "ex": "I try to be responsible and save money."},
        {"word": "Sight", "trans": "Manzara", "ex": "I saw the pyramids of Egypt. What a sight!"},
        {"word": "Spot", "trans": "Joy, makon", "ex": "The kitchen is a good spot to eat meals."},
        {"word": "Structure", "trans": "Imorat, bino", "ex": "They just built a beautiful new structure downtown."},
        {"word": "Whole", "trans": "Barcha, butun", "ex": "I ate the whole pie. We don't have any more."}
    ],
    14: [
        {"word": "Coach", "trans": "Murabbiy, trener", "ex": "My coach gets very excited during games."},
        {"word": "Control", "trans": "Nazorat qilmoq, boshqarmoq", "ex": "To control the TV, just push the buttons."},
        {"word": "Description", "trans": "Tavsif, ta'rif", "ex": "The jail cell was very small."},
        {"word": "Direct", "trans": "To'g'ridan-to'g'ri", "ex": "The green path is a direct route to my house."},
        {"word": "Exam", "trans": "Imtihon", "ex": "I did some practice questions for the math exam on the board."},
        {"word": "Example", "trans": "Misol, namuna", "ex": "Cola is an example of a soft drink."},
        {"word": "Limit", "trans": "Me'yor", "ex": "My mother put a limit on how much I could use the phone."},
        {"word": "Local", "trans": "Mahalliy", "ex": "The local market in my neighborhood sells all the food we need."},
        {"word": "Magical", "trans": "Sirli; ajoyib", "ex": "The fireworks made the night sky look so magical."},
        {"word": "Mail", "trans": "Xat, maktub; pochta", "ex": "I get a lot of mail because I have friends all over the world."},
        {"word": "Novel", "trans": "Roman", "ex": "He wrote a great novel about ancient China."},
        {"word": "Outline", "trans": "Reja", "ex": "Before I wrote my essay, I made an outline."},
        {"word": "Poet", "trans": "Shoir", "ex": "William Shakespeare was one of the greatest poets."},
        {"word": "Print", "trans": "Qog'ozga tushirmoq", "ex": "Make sure that you print your name clearly."},
        {"word": "Scene", "trans": "Epizod, sahna", "ex": "A movie is made up of many short pieces or scenes."},
        {"word": "Sheet", "trans": "Varoq", "ex": "I only needed a single sheet of paper to do my homework."},
        {"word": "Silly", "trans": "Ahmactualona, be'mani", "ex": "I made a silly mistake of dropping mom's vase."},
        {"word": "Store", "trans": "Do'kon, univermag", "ex": "I picked up a few things at the grocery store."},
        {"word": "Suffer", "trans": "Azoblanmoq, dard chekmoq", "ex": "Her headache made her suffer all day."},
        {"word": "Technology", "trans": "Texnika vositasi", "ex": "He loves technology such as laptop computers."}
    ],
    15: [
        {"word": "Across", "trans": "Narigi tomonga/da", "ex": "He walked across the board to the other side."},
        {"word": "Breathe", "trans": "Nafas olmoq", "ex": "We need strong healthy lungs to help us breathe well."},
        {"word": "Characteristic", "trans": "Fazilat, xususiyat", "ex": "One characteristic of tigers is their black stripes."},
        {"word": "Consume", "trans": "Iste'mol qilmoq, yemoq", "ex": "Jack consumed a whole plate of spaghetti."},
        {"word": "Excite", "trans": "Hayajonlantirmoq, hayajonga solmoq", "ex": "I heard about the school dance on Friday. This excited me."},
        {"word": "Extreme", "trans": "Keskin, shiddatli", "ex": "His workout was so extreme that he was sweating heavily."},
        {"word": "Fear", "trans": "Qo'rquv, vahima", "ex": "I have a great fear of skateboarding."},
        {"word": "Fortunate", "trans": "Omadli", "ex": "I was fortunate to get a seat."},
        {"word": "Happen", "trans": "Nasib qilmoq", "ex": "I happened to meet some new friends at school today."},
        {"word": "Length", "trans": "Uzunlik", "ex": "The length of the floor is three meters."},
        {"word": "Mistake", "trans": "Xato", "ex": "My boss always yells at me when I make a mistake."},
        {"word": "Observe", "trans": "Kuzatmoq, ko'rmoq", "ex": "Brian observed the sun rising over the mountains."},
        {"word": "Opportunity", "trans": "Imkoniyat, imkon", "ex": "I had an opportunity to take pictures in the jungle."},
        {"word": "Prize", "trans": "Mukofot, sovrin", "ex": "I won a for getting the best grade on my science test."},
        {"word": "Race", "trans": "Poyga", "ex": "Paul is a fast runner, so he easily won the race."},
        {"word": "Realize", "trans": "Fahmlamoq, anglamoq; to'satdan miyasiga kelmoq", "ex": "After I left my house, I realized that I left the light on."},
        {"word": "Respond", "trans": "Javob qaytarmoq", "ex": "When the teacher asked the question, we all responded."},
        {"word": "Risk", "trans": "Xavfli tavakkal", "ex": "I took a risk and climbed the snowy mountain."},
        {"word": "Wonder", "trans": "Bilishni xohlamoq", "ex": "The young mother wondered if she'd have a boy or a girl."},
        {"word": "Yet", "trans": "Hali ham, haligacha", "ex": "We can't go out yet; we're still eating."}
    ],
    16: [
        {"word": "Academy", "trans": "Akademiya", "ex": "There are many courses taught at the academy."},
        {"word": "Ancient", "trans": "Qadimiy", "ex": "I want to see the ancient buildings in Rome."},
        {"word": "Board", "trans": "Taxta", "ex": "The sign was made of a few wooden boards."},
        {"word": "Century", "trans": "Asr (100 yil), 100 yillik", "ex": "Our company is celebrating a century of business in London."},
        {"word": "Clue", "trans": "Ashyoviy dalil", "ex": "The detective found some clues on the sidewalk."},
        {"word": "Concert", "trans": "Konsert", "ex": "I enjoyed the concert last night. The band was very good."},
        {"word": "County", "trans": "Okrug (AQSH da)", "ex": "He wanted to represent the citizens of his county."},
        {"word": "Dictionary", "trans": "Lug'at", "ex": "I use the dictionary to learn new words."},
        {"word": "Exist", "trans": "Mavjud bo'lmoq", "ex": "Do you really think that unicorns ever existed?"},
        {"word": "Flat", "trans": "Tekis, silliq", "ex": "My parents bought a new flat screen TV over the weekend."},
        {"word": "Gentleman", "trans": "Jentlmen", "ex": "My grandfather is a kind and helpful gentleman."},
        {"word": "Hidden", "trans": "Yashirin", "ex": "The hidden camera recorded everything in the parking lot."},
        {"word": "Maybe", "trans": "Balki, ehtimol", "ex": "If I focus hard enough, maybe I can come up with the right answer."},
        {"word": "Officer", "trans": "Ofitser", "ex": "The soldiers followed the orders of the officer."},
        {"word": "Original", "trans": "Asl nusxadagi", "ex": "This is the original painting of the Mona Lisa."},
        {"word": "Pound", "trans": "Urmoq, qoqmoq", "ex": "He pounded the nail with the hammer."},
        {"word": "Process", "trans": "Jarayon", "ex": "Making a cake is a long process."},
        {"word": "Publish", "trans": "Chop etmoq, nashr qilmoq", "ex": "That company publishes daily newspapers."},
        {"word": "Theater", "trans": "Teatr", "ex": "We went to the theater to see a play."},
        {"word": "Wealth", "trans": "Boylik, mol-davlat", "ex": "One of the most important things to some people is wealth."}
    ],
    17: [
        {"word": "Appreciate", "trans": "Qadrlamoq; ma'nosini tushunmoq", "ex": "I can appreciate the lovely scenery."},
        {"word": "Available", "trans": "Mavjud, bor, bo'sh", "ex": "There were many seats available in the room."},
        {"word": "Beat", "trans": "Yengmoq, yengib chiqmoq", "ex": "I managed to beat everyone in the race."},
        {"word": "Bright", "trans": "Yorqin", "ex": "The bright light from the explosion hurt my eyes."},
        {"word": "Celebrate", "trans": "Nishonlamoq", "ex": "We all celebrated when we heard the great news."},
        {"word": "Determine", "trans": "Tanlamoq, qaror qilmoq", "ex": "He tried to determine which one to eat first."},
        {"word": "Disappear", "trans": "Ko'rinmay ketmoq; nari ketmoq", "ex": "The top of the building is disappearing in the clouds."},
        {"word": "Else", "trans": "Boshqa, o'zga", "ex": "I wanted a bike for my birthday, but I got something else."},
        {"word": "Fair", "trans": "Xolis, adolatli, halol", "ex": "He sold me his car for a fair price."},
        {"word": "Flow", "trans": "Oqmoq", "ex": "The water flowed over the rocks and into the lake."},
        {"word": "Forward", "trans": "Oldinga", "ex": "When he saw his mother, the baby crawled forward to her."},
        {"word": "Hill", "trans": "Tepalik, balandlik", "ex": "The sun was rising above the green hills."},
        {"word": "Level", "trans": "Daraja", "ex": "Please check the level of the temperature."},
        {"word": "Lone", "trans": "Yakka, yolg'iz", "ex": "A lone man walked along the street."},
        {"word": "Puddle", "trans": "Ko'lmak", "ex": "When the ice melted, it formed a puddle."},
        {"word": "Response", "trans": "Javob", "ex": "He asked if I was sad. My response was 'No.'"},
        {"word": "Season", "trans": "Fasl, mavsum", "ex": "Fall is a warm season, while winter is very cold."},
        {"word": "Solution", "trans": "Yechim, javob", "ex": "There are many problems. We need solutions!"},
        {"word": "Waste", "trans": "Behuda savurmoq", "ex": "Turn off the water so you don't waste it."},
        {"word": "Whether", "trans": "Mi; ...yo bo'lmasa", "ex": "I could not decide whether to go left or right."}
    ],
    18: [
        {"word": "Argue", "trans": "Tortishmoq, janjallashmoq", "ex": "We argued about where to go for dinner."},
        {"word": "Communicate", "trans": "Suhbat qurmoq", "ex": "I communicated with Paul about his new ideas."},
        {"word": "Crowd", "trans": "Omma, olamon", "ex": "A large crowd had gathered on the street to see the show."},
        {"word": "Depend", "trans": "Qaram bo'lmoq, muhtoj bo'lmoq", "ex": "Children depend on their parents for many things."},
        {"word": "Dish", "trans": "Likop, tarelka", "ex": "She put a clean white dish on the table."},
        {"word": "Empty", "trans": "Bo'sh", "ex": "My gas tank was almost empty, so I couldn't drive far."},
        {"word": "Exact", "trans": "Aniq", "ex": "Please use the exact amount of sugar for the cake."},
        {"word": "Fresh", "trans": "Yangi", "ex": "I just bought these oranges. They are very fresh."},
        {"word": "Gather", "trans": "To'plamoq, yig'moq", "ex": "Sam gathered some flowers for his mother."},
        {"word": "Indicate", "trans": "Ko'rsatmoq", "ex": "He pointed to his eyes to indicate where he had been hurt."},
        {"word": "Item", "trans": "Buyum, narsa", "ex": "I have many items for school in my bag."},
        {"word": "Offer", "trans": "Taklif qilmoq", "ex": "He offered me the keys to his car."},
        {"word": "Price", "trans": "Narx", "ex": "What is the price of this item?"},
        {"word": "Product", "trans": "Mahsulot", "ex": "My sister has many beauty products in her room."},
        {"word": "Property", "trans": "Mulk", "ex": "The house is now my property."},
        {"word": "Purchase", "trans": "Sotib olmoq", "ex": "I recently purchased a new car."},
        {"word": "Recommend", "trans": "Tavsiya qilmoq", "ex": "My doctor recommended that I get some exercise."},
        {"word": "Select", "trans": "Tanlamoq", "ex": "I hope that I selected the right answers on the test."},
        {"word": "Tool", "trans": "Asbob, anjom", "ex": "We used a tool to fix the window."},
        {"word": "Treat", "trans": "Munosabatda bo'lmoq", "ex": "The cats treated the mouse very nicely."}
    ],
    19: [
        {"word": "Alive", "trans": "Tirik, hayot", "ex": "My grandparents are still alive even though they are old."},
        {"word": "Bone", "trans": "Suyak", "ex": "I brought home a nice bone for my dog."},
        {"word": "Bother", "trans": "Harakat qilmoq, urinmoq", "ex": "No one bothered to wash the dishes today."},
        {"word": "Captain", "trans": "Kapitan", "ex": "The captain sailed his ship to Australia."},
        {"word": "Conclusion", "trans": "Yakun, nihoya", "ex": "At the conclusion of the race, the spectators cheered for the winner."},
        {"word": "Doubt", "trans": "Shubha", "ex": "I have doubt that the story is true."},
        {"word": "Explore", "trans": "Tadqiq etmoq", "ex": "He wants to explore the world and see new things."},
        {"word": "Foreign", "trans": "Yot, begona, chet", "ex": "Mexican food is a popular foreign food."},
        {"word": "Gather", "trans": "To'plamoq, yig'moq", "ex": "Sam gathered some flowers for his mother."},
        {"word": "However", "trans": "Lekin, biroq, shunga qaramasdan", "ex": "She is a great cook. However, she never had professional training."},
        {"word": "Injustice", "trans": "Adolatsizlik, nohaqlik", "ex": "Putting an innocent person in jail is an act of injustice."},
        {"word": "International", "trans": "Xalqaro", "ex": "The United Nations is a powerful international organization."},
        {"word": "Lawyer", "trans": "Huquqshunos, advokat", "ex": "The lawyer left the courthouse after the judge made her decision."},
        {"word": "Mention", "trans": "Suhbatlashmoq; ta'kidlamoq", "ex": "The doctors mentioned the problems that the patient was having."},
        {"word": "Policy", "trans": "Qoida, prinsip, qonun-qoida", "ex": "He told us that his policy was to put customers first."},
        {"word": "Social", "trans": "Ijtimoiy", "ex": "People should come together and fix the world's social problems."},
        {"word": "Speech", "trans": "Nutq", "ex": "She gave a speech to the class."},
        {"word": "Staff", "trans": "Shtat, jamoa", "ex": "My dad has a staff of four people to help him at the office."},
        {"word": "Toward", "trans": "Sari, tomon", "ex": "Santa walked toward my house with a special tree."},
        {"word": "Wood", "trans": "Yog'och", "ex": "I put the pieces of wood in a pile."}
    ],
    20: [
        {"word": "Achieve", "trans": "Erishmoq, qo'lga kiritmoq", "ex": "I was happy that I could achieve my goal."},
        {"word": "Advise", "trans": "Maslahat bermoq", "ex": "My mother often advises people about their money."},
        {"word": "Already", "trans": "Allaqachon", "ex": "It is already time for the movie to start. Let's go in."},
        {"word": "Basic", "trans": "Oddiy, sodda, oson", "ex": "I learned some basic English skills in school today."},
        {"word": "Bit", "trans": "Bo'lak, parcha, burda", "ex": "I ate a bit of chocolate before I went to bed."},
        {"word": "Consider", "trans": "Haqida o'ylamoq, o'ylab ko'rmoq", "ex": "Pete didn't like his job. He considered getting a new one."},
        {"word": "Destroy", "trans": "Vayron qilmoq, xarob qilmoq", "ex": "The glass was destroyed."},
        {"word": "Entertain", "trans": "Xursand qilmoq", "ex": "The clown entertained the kids at the party."},
        {"word": "Extra", "trans": "Qo'shimcha", "ex": "The squirrel had extra nuts for the winter."},
        {"word": "Goal", "trans": "Maqsad", "ex": "Her goal was to become a doctor."},
        {"word": "Lie", "trans": "Aldamoq, yolg'on gapirmoq", "ex": "Whenever Pinocchio lied to his father, his nose grew."},
        {"word": "Meat", "trans": "Go'sht", "ex": "This piece of meat I'm eating tastes very good."},
        {"word": "Opinion", "trans": "Fikr, mulohaza", "ex": "Meg told me her opinion of my story. She said it was not funny."},
        {"word": "Real", "trans": "Real, haqiqiy", "ex": "The handbag has a stamp on it, so it's real."},
        {"word": "Reflect", "trans": "Aks ettirmoq", "ex": "Her face was reflected on the smooth glass."},
        {"word": "Regard", "trans": "Deb hisoblamoq", "ex": "The boy regarded the girl as a good friend."},
        {"word": "Serve", "trans": "Keltirmoq, tortmoq", "ex": "He served us our drinks quickly."},
        {"word": "Vegetable", "trans": "Sabzavot", "ex": "Carrots are my favorite vegetable."},
        {"word": "War", "trans": "Urush", "ex": "Many young men died in the war."},
        {"word": "Worth", "trans": "Arziydigan", "ex": "Our house is worth a lot of money."}
    ],
    21: [
        {"word": "Appear", "trans": "Dek ko'rinmoq", "ex": "She appeared to be sad."},
        {"word": "Base", "trans": "Asos, taglik", "ex": "The base of the table has three legs."},
        {"word": "Brain", "trans": "Miya", "ex": "You must use your brain to solve the problem."},
        {"word": "Career", "trans": "Ish faoliyati", "ex": "He was in the hospitality business for most of his career."},
        {"word": "Clerk", "trans": "Do'kon yordamchisi", "ex": "The clerk added up her bill for the groceries."},
        {"word": "Effort", "trans": "Harakat, urinish", "ex": "He always puts a lot of effort into his studies."},
        {"word": "Enter", "trans": "Kirmoq", "ex": "Two guards greeted me as I entered the front door."},
        {"word": "Excellent", "trans": "Juda yaxshi, a'lo", "ex": "I got an excellent score on my school test."},
        {"word": "Hero", "trans": "Qahramon", "ex": "To children, the man in the blue and red costume was a hero."},
        {"word": "Hurry", "trans": "Shoshilmoq", "ex": "I hurried home on my bike."},
        {"word": "Inform", "trans": "Xabar bermoq", "ex": "I called and informed her about my idea."},
        {"word": "Later", "trans": "Keyinroq", "ex": "She missed the train, so she'll arrive a little later than expected."},
        {"word": "Leave", "trans": "Tark etmoq, ketmoq", "ex": "He packed his bag and was ready to leave for home."},
        {"word": "Locate", "trans": "Topmoq", "ex": "I could not locate my keys in the house."},
        {"word": "Nurse", "trans": "Hamshira", "ex": "A nurse helped me get better."},
        {"word": "Operation", "trans": "Operatsiya", "ex": "The operation on my arm was a success."},
        {"word": "Pain", "trans": "Og'riq", "ex": "His head was full of pain."},
        {"word": "Refuse", "trans": "Rad etmoq", "ex": "The dog refused to play with the cat."},
        {"word": "Though", "trans": "Ga qaramasdan, sa ham", "ex": "Though he was overweight, he liked to be active."},
        {"word": "Various", "trans": "Turli-tuman, xar-hil", "ex": "She owned shoes of various styles."}
    ],
    22: [
        {"word": "Actual", "trans": "Haqiqiy", "ex": "This is the actual sword that the King owned, not a fake."},
        {"word": "Amaze", "trans": "Hayratda qoldirmoq", "ex": "The news in the paper amazed Jack."},
        {"word": "Charge", "trans": "Narx", "ex": "The charge for the shirts was $15.00."},
        {"word": "Comfort", "trans": "Taskin bermoq, ovutmoq", "ex": "I wanted to comfort my friend after I heard the bad news."},
        {"word": "Contact", "trans": "Aloqaga chiqmoq", "ex": "I contacted Sue about my party."},
        {"word": "Customer", "trans": "Xaridor", "ex": "The customer put a few items in a bag."},
        {"word": "Deliver", "trans": "Tashimoq, eltmoq, yetkazmoq", "ex": "The man delivered Chinese food to my house."},
        {"word": "Earn", "trans": "Pul ishlab topmoq", "ex": "He earns his living as a chef in a great restaurant."},
        {"word": "Gate", "trans": "Darvoza", "ex": "We want to put up a wooden gate around our house."},
        {"word": "Include", "trans": "O'z ichiga olmoq", "ex": "Does this meal include a soft drink?"},
        {"word": "Manage", "trans": "Boshqarmoq, olib bormoq", "ex": "I had to manage the meeting myself."},
        {"word": "Mystery", "trans": "Sir, jumboq", "ex": "The path on the map was a complete mystery to me."},
        {"word": "Occur", "trans": "Yuz bermoq, sodir bo'lmoq", "ex": "When did the thunderstorm occur?"},
        {"word": "Opposite", "trans": "Teskari, zid", "ex": "The opposite of black is white."},
        {"word": "Plate", "trans": "Likop", "ex": "I put my plate down so I could put some food on it."},
        {"word": "Receive", "trans": "Olmoq, qabul qilib olmoq", "ex": "I received a present on my birthday."},
        {"word": "Reward", "trans": "Mukofot, sovrin", "ex": "He was given a reward for his excellent performance."},
        {"word": "Set", "trans": "Qo'ymoq", "ex": "Please set the dice down on the table."},
        {"word": "Steal", "trans": "O'g'irlamoq", "ex": "The men tried to steal money from the bank."},
        {"word": "Thief", "trans": "O'g'ri", "ex": "A thief broke into our home and took my mother's jewelry."}
    ],
    23: [
        {"word": "Advance", "trans": "Oldinga yurmoq", "ex": "He advanced up the ladder slowly."},
        {"word": "Athlete", "trans": "Sportchi", "ex": "Some athletes can play many sports very well."},
        {"word": "Average", "trans": "O'rtacha, o'rta tabaqali", "ex": "I'm not rich or poor; I'm average."},
        {"word": "Behavior", "trans": "Xulq-atvor", "ex": "Their behavior was good this semester. They didn't cause trouble."},
        {"word": "Behind", "trans": "Orqasida", "ex": "The little girl was hiding behind a tree."},
        {"word": "Course", "trans": "Dars, kurs", "ex": "I took a P.E. course in school this year."},
        {"word": "Lower", "trans": "Pasaymoq, pasaytirmoq", "ex": "The chart shows how his production has lowered."},
        {"word": "Match", "trans": "Mos kelmoq, tushmoq", "ex": "The two shoes matched. They looked the same."},
        {"word": "Member", "trans": "A'zo", "ex": "Julie is the newest member of our team."},
        {"word": "Mental", "trans": "Aqliy, faraziy", "ex": "I made a mental picture of the room."},
        {"word": "Passenger", "trans": "Yo'lovchi", "ex": "One passenger was standing in the subway train."},
        {"word": "Personality", "trans": "Shaxsiyat, o'zlik", "ex": "John has a bad personality."},
        {"word": "Poem", "trans": "Sher, to'rtlik", "ex": "William Shakespeare wrote many poems."},
        {"word": "Pole", "trans": "Ustun, xoda", "ex": "The flag was hanging from the flag pole."},
        {"word": "Remove", "trans": "Olib tashlamoq", "ex": "I removed the nail from the board."},
        {"word": "Safety", "trans": "Xavfsizlik", "ex": "For his own safety, he was placed in a car seat."},
        {"word": "Shoot", "trans": "Otmoq, o'q uzmoq", "ex": "The hunter raised his gun to shoot at the target."},
        {"word": "Sound", "trans": "Tovush chiqarmoq", "ex": "The alarm clock sounded and woke us all up."},
        {"word": "Swim", "trans": "Suzmoq, cho'milmoq", "ex": "I love to swim in the ocean."},
        {"word": "Web", "trans": "O'rgimchak to'ri/uyasi", "ex": "Mom cleaned the spider webs out of the garage."}
    ],
    24: [
        {"word": "Block", "trans": "Bo'lak", "ex": "I saw a block of ice on the floor."},
        {"word": "Cheer", "trans": "Qichqirmoq, ruhlantirmoq", "ex": "The crowd all cheered when the home team won."},
        {"word": "Complex", "trans": "Murakkab, mushkul", "ex": "A jig-saw puzzle can be complex because it has so many parts."},
        {"word": "Critic", "trans": "Tanqidchi", "ex": "The wine critic tasted the wine so he could give his opinion."},
        {"word": "Event", "trans": "Tadbir, voqea", "ex": "Finishing high school was a major event in his life."},
        {"word": "Exercise", "trans": "Mashq qilmoq", "ex": "You should exercise every day."},
        {"word": "Fit", "trans": "Loyiq bo'lmoq, mos kelmoq", "ex": "The colorful eggs fit into the box."},
        {"word": "Friendship", "trans": "Do'stlik", "ex": "Michael and Lisa have a very strong friendship with each other."},
        {"word": "Guide", "trans": "Gid, yo'lboshchi", "ex": "We followed a guide at the park."},
        {"word": "Lack", "trans": "Yetishmovchilik, kamchilik", "ex": "His only problem is a lack of money."},
        {"word": "Passage", "trans": "Yo'lak", "ex": "The long passage led us to the other side of the field."},
        {"word": "Perform", "trans": "Ijro etmoq", "ex": "He will perform a song for the class."},
        {"word": "Pressure", "trans": "Bosim", "ex": "They put pressure on him to change his mind."},
        {"word": "Probable", "trans": "Ehtimol, bo'lishi mumkin bo'lgan", "ex": "It is probable that you will get a good grade if you study for the test."},
        {"word": "Public", "trans": "Ijtimoiy, hamma uchun", "ex": "I went to the public park to play with my friends."},
        {"word": "Strike", "trans": "Urmoq", "ex": "She struck the other girl in the face."},
        {"word": "Support", "trans": "Qo'llab quvvatlamoq", "ex": "Everyone at work supports the new plan."},
        {"word": "Task", "trans": "Topshiriq, vazifa", "ex": "Who has the task of building the brick wall?"},
        {"word": "Term", "trans": "Termin, so'z", "ex": "I often use the term \"oops\" when I make a mistake."},
        {"word": "Unite", "trans": "Birlashmoq", "ex": "If we unite, we can finish our project faster."}
    ],
    25: [
        {"word": "Associate", "trans": "Bog'lamoq", "ex": "Most people associate birthday parties with having fun."},
        {"word": "Environment", "trans": "Tabiat, atrof-muhit", "ex": "Keeping our environment clean is important to our health."},
        {"word": "Factory", "trans": "Fabrika, zavod", "ex": "We have only one factory in our town."},
        {"word": "Feature", "trans": "Xususiyat, jihat", "ex": "The cell phone has many features."},
        {"word": "Instance", "trans": "Namuna, misol", "ex": "I have never experienced an instance of hate. Have you?"},
        {"word": "Involve", "trans": "Jalb etmoq", "ex": "The whole family was involved in playing the game."},
        {"word": "Medicine", "trans": "Dori-darmon", "ex": "The doctor gave me medicine for my cold."},
        {"word": "Mix", "trans": "Aralashma", "ex": "The green mix we made in science class spilled onto the table."},
        {"word": "Organize", "trans": "Tashkillashtirmoq", "ex": "Make a list to help you organize the things you need."},
        {"word": "Period", "trans": "Davr, zamon", "ex": "In one period in Europe, there were many knights."},
        {"word": "Populate", "trans": "Yashamoq", "ex": "Billions of people populate the Earth."},
        {"word": "Produce", "trans": "Ishlab chiqarmoq", "ex": "This tree produces apples every year."},
        {"word": "Range", "trans": "Qator, miqdor", "ex": "I saw a range of cars to choose from."},
        {"word": "Recognize", "trans": "Tanimoq, bilmoq", "ex": "I recognized an old friend from many years ago."},
        {"word": "Regular", "trans": "Muntazam", "ex": "Our regular lunch time is around noon."},
        {"word": "Sign", "trans": "Belgi, ishora", "ex": "The sign indicated that today would be a bad day."},
        {"word": "Tip", "trans": "Uch", "ex": "The tip of his pen was very sharp."},
        {"word": "Tradition", "trans": "An'ana, udum", "ex": "Marriage is a tradition all over the world."},
        {"word": "Trash", "trans": "Axlat, chiqindi", "ex": "Please take out the trash; it smells bad."},
        {"word": "Wide", "trans": "Keng", "ex": "The door was as wide as the hallway."}
    ],
    26: [
        {"word": "Advice", "trans": "Maslahat", "ex": "I don't know how to study for my exams. Can you give me some advice?"},
        {"word": "Along", "trans": "Bo'ylab", "ex": "Walk along this tunnel for ten minutes, and you'll see a door."},
        {"word": "Attention", "trans": "Diqqat, e'tibor", "ex": "His work got the attention of two of his co-workers."},
        {"word": "Attract", "trans": "Tortmoq, jalb qilmoq", "ex": "The magnet attracted the metal."},
        {"word": "Climb", "trans": "Tirmashmoq, chirmashmoq", "ex": "The girls climbed to the top of the mountain."},
        {"word": "Drop", "trans": "Tomchilamoq, tommoq", "ex": "A small amount of water dropped from the bottle."},
        {"word": "Final", "trans": "Oxirgi, so'nggi", "ex": "In the final part of the film, the man and the woman got married."},
        {"word": "Further", "trans": "Uzunroq, uzoqroq", "ex": "The escalator is further along than I thought."},
        {"word": "Imply", "trans": "Nazarda tutmoq, ko'zda tutmoq", "ex": "The man implied that he wanted the job, but he didn't say it."},
        {"word": "Maintain", "trans": "Ayni holda saqlamoq", "ex": "The balls maintain constant movement."},
        {"word": "Neither", "trans": "Hech qaysisi, hech bir", "ex": "Neither the pass on the left nor the pass on the right will lead us home."},
        {"word": "Otherwise", "trans": "Aks holda", "ex": "It's good to stay active; otherwise, you'll gain weight."},
        {"word": "Physical", "trans": "Jismoniy", "ex": "Biking is good for your physical health."},
        {"word": "Prove", "trans": "Isbotlamoq, dalil keltirmoq", "ex": "My teacher proved the answer on the board."},
        {"word": "React", "trans": "Hodisaga munosabat bildirmoq", "ex": "James reacted badly to the news."},
        {"word": "Ride", "trans": "Haydamoq, minmoq", "ex": "I will ride a roller-coaster for the first time today."},
        {"word": "Situated", "trans": "Joylashgan, o'rnashgan", "ex": "The white board is situated between the two men."},
        {"word": "Society", "trans": "Jamiyat", "ex": "Society expects people to be good and honest."},
        {"word": "Standard", "trans": "Standard, me'zon", "ex": "This older model TV is below our store's standards."},
        {"word": "Suggest", "trans": "Taklif qilmoq, tavsiya qilmoq", "ex": "He suggested that we go to see his boss."}
    ],
    27: [
        {"word": "Actually", "trans": "Aslida, rosti", "ex": "My dad looks a little mean, but actually he's very kind."},
        {"word": "Bite", "trans": "Tishlamoq", "ex": "The boy took a big bite out of his hamburger."},
        {"word": "Coast", "trans": "Sohil, qirg'oq", "ex": "I stayed on the southern coast of Australia."},
        {"word": "Deal", "trans": "Kelishuv, shartnoma", "ex": "I made a deal with the other company to give us some space."},
        {"word": "Desert", "trans": "Cho'l", "ex": "Not many plants grow in the desert."},
        {"word": "Earthquake", "trans": "Zilzila", "ex": "The building shook during the earthquake."},
        {"word": "Effective", "trans": "Samarali", "ex": "Swimming is an effective way to stay healthy."},
        {"word": "Examine", "trans": "Tekshirib ko'rmoq", "ex": "The doctor examined my eyes today."},
        {"word": "False", "trans": "Noto'g'ri, xato", "ex": "If you think the answer is false, press the red button."},
        {"word": "Gift", "trans": "Hadiya, sovg'a", "ex": "Dave received many gifts for Christmas."},
        {"word": "Hunger", "trans": "Ochlik", "ex": "After playing all day long, he was filled with hunger."},
        {"word": "Imagine", "trans": "Tasavvur qilmoq", "ex": "Sally imagined herself winning lots of money."},
        {"word": "Journey", "trans": "Sayohat", "ex": "I went on a journey across the country with my parents."},
        {"word": "Puzzle", "trans": "Boshqotirma", "ex": "The question was a puzzle to him."},
        {"word": "Quite", "trans": "Juda, rosa", "ex": "I think typing on a keyboard is quite easy."},
        {"word": "Rather", "trans": "Ma'qul ko'rmoq", "ex": "I would rather have the red one than the blue one."},
        {"word": "Specific", "trans": "Aniq, muayyan", "ex": "Please choose a specific place on the map."},
        {"word": "Tour", "trans": "Safar, sayohat", "ex": "I took a tour of Asia and Europe."},
        {"word": "Trip", "trans": "Sayohat, safar", "ex": "Ken took a trip to the city yesterday."},
        {"word": "Value", "trans": "Qiymat, baho", "ex": "Matthew found a treasure chest full of gold."}
    ],
    28: [
        {"word": "Band", "trans": "Musiqiy guruh", "ex": "My brother is in a rock band."},
        {"word": "Barely", "trans": "Arang; sal-pal", "ex": "I barely had enough money to pay for my bus ticket."},
        {"word": "Boring", "trans": "Zerikarli", "ex": "I think the Internet is boring."},
        {"word": "Cancel", "trans": "Bekor qilmoq", "ex": "She cancelled the rest of her plans because of the rain."},
        {"word": "Driveway", "trans": "Tratuar, yo'lak", "ex": "The long driveway led us to their new house."},
        {"word": "Garbage", "trans": "Chiqindi, axlat", "ex": "The boy cleaned up the garbage around his house."},
        {"word": "Instrument", "trans": "Asbob", "ex": "My favorite musical instrument is the piano."},
        {"word": "List", "trans": "Ro'yhat", "ex": "My mom makes a list of groceries to buy."},
        {"word": "Magic", "trans": "Sehr, jodu", "ex": "The magician used magic to pull a rabbit out of his hat."},
        {"word": "Message", "trans": "Xabar", "ex": "I left a message for you in the envelope."},
        {"word": "Notice", "trans": "Payqamoq, sezmoq", "ex": "Did you notice the view?"},
        {"word": "Own", "trans": "Egalik qilmoq", "ex": "My grandfather owns that house."},
        {"word": "Predict", "trans": "Bashorat qilmoq, oldindan aytmoq", "ex": "She predicted that I would get married next year."},
        {"word": "Professor", "trans": "Professor", "ex": "Mike's science professor knows a lot about physics."},
        {"word": "Rush", "trans": "Yelmoq; shoshmoq", "ex": "Nancy rushed to finish her homework."},
        {"word": "Schedule", "trans": "Jadval", "ex": "What is your class schedule for today?"},
        {"word": "Share", "trans": "Bo'lishmoq, baham ko'rmoq", "ex": "Jimmy shared his apple with me."},
        {"word": "Stage", "trans": "Sahna", "ex": "A large screen was on the stage."},
        {"word": "Storm", "trans": "Bo'ron, to'fon", "ex": "Did that storm wake you up last night?"},
        {"word": "Within", "trans": "Ichida", "ex": "Within the box, there was a pizza."}
    ],
    29: [
        {"word": "Advertise", "trans": "reklama qilmoq", "ex": "They used a rabbit to help them advertise their product."},
        {"word": "Assign", "trans": "tayinlamoq, topshiriq", "ex": "I assigned the worker an important task."},
        {"word": "Audience", "trans": "auditoriya", "ex": "There was a large audience at the game."},
        {"word": "Breakfast", "trans": "nonushta", "ex": "She cancelled the rest of her plans because of the rain."},
        {"word": "Competition", "trans": "musobaqa", "ex": "He won the running competition over the weekend."},
        {"word": "Cool", "trans": "salqin, jindak sovuq", "ex": "The weather is cool in the fall."},
        {"word": "Gain", "trans": "olmoq, oshirmoq", "ex": "I gained some weight over the summer."},
        {"word": "Importance", "trans": "ahamiyat", "ex": "VIPs are people of great importance."},
        {"word": "Knowledge", "trans": "bilim", "ex": "A music teacher should have good knowledge of music."},
        {"word": "Major", "trans": "muhim, katta", "ex": "I have a major problem. My boss wants to redo my plan."},
        {"word": "Mean", "trans": "baxil, ziqna", "ex": "My co-worker is a very mean person. He gets angry very quickly."},
        {"word": "Prefer", "trans": "ma'qul ko'rmoq", "ex": "I prefer to take the path that will lead me to a bright future."},
        {"word": "President", "trans": "prezident", "ex": "The president of our country made an important announcement."},
        {"word": "Progress", "trans": "siljish, o'sish", "ex": "Our company made financial progress this year."},
        {"word": "Respect", "trans": "hurmat", "ex": "I have great respect for firemen."},
        {"word": "Rich", "trans": "badavlat", "ex": "He's rich. He can buy anything he wants."},
        {"word": "Skill", "trans": "mahorat, qobiliyat", "ex": "A snowboarder must have the right skills to do well."},
        {"word": "Somehow", "trans": "bir amallab", "ex": "He somehow had to find a way to reach the life preservation."},
        {"word": "Strength", "trans": "kuch, quvvat", "ex": "Exercising will increase your strength and give you more things."},
        {"word": "Vote", "trans": "ovoz bermoq", "ex": "I voted for Billy to be our class president."}
    ],
    30: [
        {"word": "Above", "trans": "tepasida", "ex": "He straightened the sign that was above the crowd."},
        {"word": "Ahead", "trans": "old tarafida", "ex": "The blue car drove on ahead of us."},
        {"word": "Amount", "trans": "miqdor", "ex": "Can I use my card to pay for the entire amount?"},
        {"word": "Belief", "trans": "ishonch", "ex": "A preacher or priest should have a strong belief in God."},
        {"word": "Center", "trans": "markaz", "ex": "The center of a dart board is the most important spot."},
        {"word": "Common", "trans": "odatiy", "ex": "It is common for snow to fall in the winter."},
        {"word": "Cost", "trans": "narx turmoq", "ex": "These designer shoes cost more than the regular ones."},
        {"word": "Demonstrate", "trans": "ko'rsatmoq", "ex": "She demonstrated her plan to her co-workers."},
        {"word": "Different", "trans": "turlicha, o'zgacha", "ex": "Each of my sisters has a different hair style from one another."},
        {"word": "Evidence", "trans": "dalil, isbot", "ex": "He used the pictures as evidence that UFOs are real."},
        {"word": "Honesty", "trans": "odillik, oqillik", "ex": "A courtroom should be a place of honesty."},
        {"word": "Idiom", "trans": "idioma", "ex": "The idiom \"when pigs fly\" means that something will never happen."},
        {"word": "Independent", "trans": "mustaqil", "ex": "She chose to live an independent life in the country."},
        {"word": "Inside", "trans": "ichki qism", "ex": "The inside of the box was empty."},
        {"word": "Master", "trans": "master, usta", "ex": "My brother is a master of taekwondo."},
        {"word": "Memory", "trans": "xotira, yod", "ex": "The memory of my first time in the city will always be the best."},
        {"word": "Proper", "trans": "odobdan, o'rinli", "ex": "It is not proper to throw your garbage on the road."},
        {"word": "Scan", "trans": "qarab chiqmoq", "ex": "You must scan each person closely."},
        {"word": "Section", "trans": "qism, bo'lim", "ex": "The green section of the graph is the most important part."},
        {"word": "Surface", "trans": "yuza, sirt", "ex": "The surface of the moon is very rough."}
    ]
}
